//! V42 F6 (#131) — the generator for `src/lib/generated/`.
//!
//! Two frontend surfaces used to be hand-matched to Rust and are now emitted
//! from it, on the pattern `settings::codegen` established in Phase E: a test
//! writes the file, the file is committed, and CI regenerates and diffs it, so
//! an uncommitted regeneration fails the build instead of shipping a stale
//! mirror.
//!
//!  * `events.ts` — the Tauri event names and their payload types, from
//!    [`super::events::ALL`]. The names the frontend listens on are now the
//!    names the backend emits, by construction.
//!  * `tools.ts` — the Tools tab's reference lists, from
//!    [`super::toolref`]. The set of tools documented is pinned to the set of
//!    tools that exists (see that module's tripwires).
//!
//! Test-cfg only, like Phase E's: nothing about the shipped binary changes.
//!
//! **A separate directory from `settings/generated/`, deliberately.** That one
//! is the `Settings` tree's ts-rs output and `settings/types.ts` re-exports it
//! as the settings wire surface. These two are neither settings nor ts-rs, and
//! filing them under `settings/` would make "what is in this directory" stop
//! meaning anything. Both directories are `-text` in `.gitattributes` and both
//! are named in the CI diff step.

use std::path::{Path, PathBuf};

use super::events::{Delivery, ALL};
use super::toolref::{ToolRef, GRAPH_TOOLS, OFFLOAD_TOOLS};

/// `<repo>/src/lib/generated`, resolved from the crate manifest so the test
/// does not depend on the working directory `cargo test` was launched in.
fn generated_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("src")
        .join("lib")
        .join("generated")
}

/// Writes `bytes` only if they differ, so a green run leaves mtimes alone.
///
/// LF endings are written explicitly and pinned by a `.gitattributes` rule for
/// this directory, for the same reason Phase E's directory has one: the
/// committed bytes have to be what a Linux CI runner regenerates, and an
/// `autocrlf=true` Windows checkout that rewrote them would fail the CI diff
/// for a reason that has nothing to do with drift.
fn write_if_changed(path: &Path, contents: &str) {
    let normalised = contents.replace("\r\n", "\n");
    if std::fs::read_to_string(path).is_ok_and(|old| old == normalised) {
        return;
    }
    std::fs::write(path, normalised.as_bytes()).expect("write generated file");
}

/// The banner every generated file opens with.
fn header(from: &str, what: &str) -> String {
    format!(
        "// GENERATED FILE — DO NOT EDIT.\n\
         //\n\
         // {what}\n\
         //\n\
         // Written by `src-tauri/src/service/codegen.rs` from\n\
         // `src-tauri/src/{from}`, and re-generated by CI, which then diffs this\n\
         // directory byte-exactly. Edit the Rust table, run `cargo test`, and commit\n\
         // what changes here.\n\n"
    )
}

/// A JavaScript single-quoted string literal.
///
/// Only two characters can end the literal early, and both are escaped. The
/// doc/description text in the source tables is prose — em dashes, curly
/// apostrophes, backticks — and all of it is valid UTF-8 inside a `'…'`
/// literal, so nothing else needs touching. A newline would, which is why
/// `toolref`'s `every_reference_row_is_substantive` refuses one.
fn js_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            _ => out.push(c),
        }
    }
    out.push('\'');
    out
}

/// Wrap `text` into `/** … */` comment lines at a fixed column.
///
/// Deterministic by construction — a greedy fill over whitespace-split words,
/// no locale, no hashing — which is what the byte-stability test needs. Words
/// longer than the budget get their own line rather than being broken.
fn doc_comment(text: &str, indent: &str) -> String {
    const WIDTH: usize = 88;
    let budget = WIDTH.saturating_sub(indent.len() + 4);
    let mut lines: Vec<String> = Vec::new();
    let mut current = String::new();
    for word in text.split_whitespace() {
        if current.is_empty() {
            current.push_str(word);
        } else if current.chars().count() + 1 + word.chars().count() <= budget {
            current.push(' ');
            current.push_str(word);
        } else {
            lines.push(std::mem::take(&mut current));
            current.push_str(word);
        }
    }
    if !current.is_empty() {
        lines.push(current);
    }
    if lines.len() == 1 {
        return format!("{indent}/** {} */\n", lines[0]);
    }
    let mut out = format!("{indent}/**\n");
    for line in &lines {
        out.push_str(&format!("{indent} * {line}\n"));
    }
    out.push_str(&format!("{indent} */\n"));
    out
}

/// Render `src/lib/generated/events.ts`.
fn render_events() -> String {
    let mut out = header(
        "service/events.rs",
        "Every Tauri event the backend emits: its name as a constant, and its\n\
         // payload type. Import the constants — `listen('a-literal')` is refused by\n\
         // `src/lib/eventNames.test.ts`, because a misspelled name fails silently.",
    );

    for def in ALL {
        let delivery = match def.delivery {
            Delivery::Broadcast => "Broadcast to every webview.",
            Delivery::Window => "Sent to ONE window by label, not broadcast.",
        };
        out.push_str(&doc_comment(&format!("{} {delivery}", def.doc), ""));
        out.push_str(&format!(
            "export const {} = {};\n\n",
            def.ts,
            js_string(def.name)
        ));
    }

    out.push_str(&doc_comment(
        "The payload each event carries. `unknown` means the frontend has no single type \
         for it — see the Rust row for why — and those listeners keep their own explicit \
         `listen<…>` generic.",
        "",
    ));
    out.push_str("export interface EventPayloadMap {\n");
    for def in ALL {
        out.push_str(&format!(
            "  {}: {};\n",
            js_string(def.name),
            def.payload
        ));
    }
    out.push_str("}\n\n");

    out.push_str(&doc_comment("Every event name the backend can emit.", ""));
    out.push_str("export type CimpEventName = keyof EventPayloadMap;\n");
    out
}

/// Render one `ToolRef[]` literal.
fn render_tool_list(name: &str, rows: &[ToolRef]) -> String {
    let mut out = format!("export const {name}: readonly ToolRef[] = [\n");
    for r in rows {
        out.push_str("  {\n");
        out.push_str(&format!("    name: {},\n", js_string(r.name)));
        out.push_str(&format!("    desc: {},\n", js_string(r.desc)));
        out.push_str(&format!("    example: {},\n", js_string(r.example)));
        out.push_str("  },\n");
    }
    out.push_str("];\n");
    out
}

/// Render `src/lib/generated/tools.ts`.
fn render_tools() -> String {
    let mut out = header(
        "service/toolref.rs",
        "The Tools tab's reference lists. The SET of names here is pinned to the\n\
         // real tool tables by `service::toolref`'s tests, in both directions — the\n\
         // hand-written mirror that drifted (#113, D1) no longer exists.",
    );
    out.push_str(&doc_comment(
        "One rendered reference row. Structurally identical to `ToolsReference.svelte`'s \
         own prop type.",
        "",
    ));
    out.push_str("export interface ToolRef {\n  name: string;\n  desc: string;\n  example: string;\n}\n\n");
    out.push_str(&doc_comment(
        "The `graph_*` / `context_*` tools the code graph exposes to AI tabs and the offload \
         worker while the graph is enabled.",
        "",
    ));
    out.push_str(&render_tool_list("GRAPH_TOOLS", GRAPH_TOOLS));
    out.push('\n');
    out.push_str(&doc_comment(
        "The tools the offload feature provides: the MCP tools an AI tab calls to delegate, \
         plus the native tools the local worker uses to complete the task (toggle them in \
         Settings → Offload task tools → Tools).",
        "",
    ));
    out.push_str(&render_tool_list("OFFLOAD_TOOLS", OFFLOAD_TOOLS));
    out
}

/// Writes both generated files.
#[test]
fn frontend_bindings_are_generated() {
    let dir = generated_dir();
    std::fs::create_dir_all(&dir).expect("create generated dir");
    write_if_changed(&dir.join("events.ts"), &render_events());
    write_if_changed(&dir.join("tools.ts"), &render_tools());
}

/// The generator is a no-op on a second run: `cargo test` twice in a row must
/// not produce a diff, or the CI check would fail on every unrelated PR.
///
/// Byte-stability is not free. Both renderers walk `&'static [..]` slices in
/// declaration order and the wrap is a greedy fill with no state, so the only
/// way this regresses is a future addition that iterates something unordered —
/// which is the whole reason the test exists rather than being assumed.
#[test]
fn regenerating_the_frontend_bindings_changes_nothing() {
    assert_eq!(render_events(), render_events(), "events.ts is not deterministic");
    assert_eq!(render_tools(), render_tools(), "tools.ts is not deterministic");
}

/// The emitted text carries no CR bytes.
///
/// `.gitattributes` marks this directory `-text`, so a CR here would make CI's
/// byte-exact diff fail on every Windows run for a reason that has nothing to
/// do with drift — the exact failure Phase E's directory hit and now guards
/// against in the same way.
#[test]
fn the_generated_text_is_lf_only() {
    for (what, text) in [("events.ts", render_events()), ("tools.ts", render_tools())] {
        assert!(
            !text.contains('\r'),
            "the generator put a CR byte into {what}; the committed bytes are LF"
        );
        assert!(text.ends_with('\n'), "{what} does not end with a newline");
    }
}

/// Every constant, name and payload type in the rendered `events.ts` really is
/// there — the emitter is not silently dropping rows.
///
/// A renderer that emitted an empty file would satisfy a byte-stability test
/// and a CR test both. This is the one that says the output has the content.
#[test]
fn the_rendered_events_declare_every_row() {
    let ts = render_events();
    for def in ALL {
        assert!(
            ts.contains(&format!("export const {} = '{}';", def.ts, def.name)),
            "`{}` is missing from the rendered events.ts",
            def.ts
        );
        assert!(
            ts.contains(&format!("  '{}': {};", def.name, def.payload)),
            "`{}`'s payload row is missing from `EventPayloadMap`",
            def.name
        );
    }
}

/// Same, for the tool reference: every row's name reaches the rendered file.
#[test]
fn the_rendered_tools_declare_every_row() {
    let ts = render_tools();
    assert!(!GRAPH_TOOLS.is_empty() && !OFFLOAD_TOOLS.is_empty());
    for r in GRAPH_TOOLS.iter().chain(OFFLOAD_TOOLS.iter()) {
        assert!(
            ts.contains(&format!("name: '{}',", r.name)),
            "`{}` is missing from the rendered tools.ts",
            r.name
        );
    }
}

/// The string escaper closes what it opens.
///
/// The reference prose is full of apostrophes (`"this session's"`), and one
/// unescaped quote would emit a file that does not parse — caught by
/// `svelte-check`, but a build after a commit rather than at the generator.
#[test]
fn the_string_escaper_handles_quotes_and_backslashes() {
    assert_eq!(js_string("plain"), "'plain'");
    assert_eq!(js_string("this session's"), "'this session\\'s'");
    assert_eq!(js_string("a\\b"), "'a\\\\b'");
    assert_eq!(js_string("em — dash, curly ’"), "'em — dash, curly ’'");
    // …and the real tables go through it without producing a stray terminator.
    for r in GRAPH_TOOLS.iter().chain(OFFLOAD_TOOLS.iter()) {
        for field in [r.name, r.desc, r.example] {
            let lit = js_string(field);
            let inner = &lit[1..lit.len() - 1];
            let mut chars = inner.chars().peekable();
            while let Some(c) = chars.next() {
                if c == '\\' {
                    chars.next();
                } else {
                    assert_ne!(c, '\'', "`{field}` emits an unescaped quote");
                }
            }
        }
    }
}
