//! V35 Phase I — **CHP, the cImp Harness Protocol**: the name, the version and
//! the capability handshake for the wire both harnesses have already been
//! speaking for a year.
//!
//! # What was already there
//!
//! The Claude hook shims and `tabs/config.rs::opencode_plugin_source` POST the
//! same harness-neutral body to the same loopback routes, discriminated by
//! `agent`. That is a protocol; nobody had named, versioned or written it down.
//! Phase I does exactly those three things and **changes no behavior**: `chp` is
//! additive and tolerated-absent, `/session/hello` is new and nothing gates on
//! what it says (locked decision 5 — negotiation becomes load-bearing in
//! Phase L). (Phase J then deleted those shims: Claude's half of the wire is now
//! `type: "http"` hooks posting Claude's own payloads to `/claude/hook/*`, with
//! the envelope in headers — see [`crate::harness::claude::hook`].)
//!
//! The written contract is [`docs/CHP.md`](../../../../docs/CHP.md). It and
//! [`CHP_VERSION`] are kept in step by [`tests::the_doc_states_this_version`],
//! the same `include_str!` two-sources-of-truth idiom the rest of the crate
//! uses.
//!
//! # Why a version on the wire (design D5)
//!
//! The generated plugin and the `--settings` overlay are **spawn-baked**: an
//! upgraded binary with an old tab still running has an *old plugin on disk*
//! talking to *new loopback code*. V32 recorded that as a deploy trap four
//! separate times (F-13, M-16, F-23, F-32's child half), each with the same
//! mitigation — "needs a FRESH TAB or it reads as a failure". With `chp` on the
//! wire the mismatch is **detected and reported** instead of surfacing as a
//! mysterious functional failure during a live-verify. That detection is this
//! module's second half ([`stale_for`]), and the *Harness health* panel is its
//! consumer.
//!
//! # One file, on purpose
//!
//! The plugin-architecture design lays out `harness/chp/{mod,events,routes}.rs`.
//! That split belongs to **Phase K**, which moves `oob/*` and the five shims
//! into `harness/<id>/` and is the point at which a directory earns its
//! subdivision. Splitting three near-empty modules out now would be structure
//! without content — and the handlers stay in `offload/loopback.rs` regardless
//! (design § 4: *"route table; handlers stay in offload/loopback.rs"*).

use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::sync::{Mutex, OnceLock, PoisonError};

// ── the version ─────────────────────────────────────────────────────────────

/// **The** CHP version, spelled once.
///
/// Substituted into the generated OpenCode plugin at generation time
/// (`tabs::config::opencode_plugin_source`) rather than typed there as a
/// literal, echoed by `/session/hello`'s ack, and asserted equal to the version
/// in `docs/CHP.md`'s header. Bumping it is therefore a three-line change in one
/// commit, and forgetting the doc fails the build.
///
/// **Compatibility is permanent, not versioned-away.** A plugin file written at
/// tab launch outlives the binary that wrote it, so every `chp` value that has
/// ever shipped must keep being *understood* — the point of the field is to make
/// the mismatch legible, never to refuse an old artifact (design § 8).
pub const CHP_VERSION: u32 = 2;

/// What an absent `chp` field means: a **pre-CHP** artifact — a plugin or shim
/// generated by a build from before Phase I.
///
/// Absent is never an error. Global principle 5 in the other direction: this is
/// the one case where "missing" has a real, specific meaning rather than being a
/// blank that should be rejected, and the meaning is *old*, not *broken*.
pub const PRE_CHP: u32 = 0;

// ── the route surface ───────────────────────────────────────────────────────

/// The capability-negotiation route (design D3). New in Phase I.
pub const HELLO_ROUTE: &str = "/session/hello";

/// One CHP event: the name L3 will gate against (design D4) and the loopback
/// route that carries it today.
///
/// `core` is D4's small set every harness must serve to be usable at all;
/// everything else is optional and a capability declares its dependency on it.
/// `live` says whether cImp serves the route **today** — a `false` row is
/// reserved for Phase L (push the read path), and is in this table so the
/// vocabulary is one list rather than a live half plus a design doc.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Event {
    pub id: &'static str,
    pub core: bool,
    pub route: &'static str,
    pub live: bool,
}

const fn ev(id: &'static str, core: bool, route: &'static str, live: bool) -> Event {
    Event {
        id,
        core,
        route,
        live,
    }
}

/// D4's core set: `hello`, `prompt`, `assistant_text`, `session_end`.
pub const EV_HELLO: &str = "hello";
pub const EV_PROMPT: &str = "prompt";
pub const EV_ASSISTANT_TEXT: &str = "assistant_text";
pub const EV_SESSION_END: &str = "session_end";

/// The optional set that is live today.
pub const EV_CONTEXT_COMPACTION: &str = "context.compaction";
pub const EV_CONTEXT_SHOULD_READ: &str = "context.should_read";
pub const EV_CONTEXT_POST_EDIT: &str = "context.post_edit";
pub const EV_MEMORY_EVENT: &str = "memory.event";
pub const EV_PERMISSION_EVENT: &str = "permission.event";
pub const EV_TAINT_BEACON: &str = "taint.beacon";
pub const EV_TOOL_GATE: &str = "tool.gate";
pub const EV_CHECKPOINT_PRE_MUTATION: &str = "checkpoint.pre_mutation";
pub const EV_CONTRACT_DRIFT: &str = "contract.drift";

/// …and the optional set Phase L will add, named here so the vocabulary is
/// complete and `docs/CHP.md` documents one table rather than two.
pub const EV_SESSION_USAGE: &str = "session.usage";
pub const EV_SESSION_TOOL_RESULT: &str = "session.tool_result";
pub const EV_SESSION_SUBAGENT: &str = "session.subagent";
pub const EV_SESSION_CONTEXT: &str = "session.context";

/// …and the neutral set V40 Phase C adds (locked decision 30).
///
/// **Additive only, and reserved to a one.** Every one of these names something
/// core already knows but only in one harness's vocabulary: the activity edges
/// are `StateSignal::ClaudeOutput*` (Phase D renames them), the sub-agent count
/// is `AgentsActiveChanged`, the permission edges are the neutral half of what
/// `harness/claude/hook.rs` classifies today, `turn.usage` is the reading
/// `usage/` + `statusline/` produce from a Claude-shaped payload, and `drift` is
/// what a reader reports when a contract moved under it.
///
/// They are declared here **before** their producers exist on purpose, and that
/// is what the `live` column is for: the vocabulary is the thing L3 gates
/// against, so it has to be one list rather than a live half plus a design doc.
/// Phase D wires the producers; nothing in this build posts to these routes and
/// `is_push_route` answers `false` for all of them.
pub const EV_HARNESS_OUTPUT_STARTED: &str = "harness.output_started";
pub const EV_HARNESS_OUTPUT_STOPPED: &str = "harness.output_stopped";
pub const EV_SUBAGENTS_ACTIVE: &str = "subagents.active";
pub const EV_PERMISSION_DETECTED: &str = "permission.detected";
pub const EV_PERMISSION_RESOLVED: &str = "permission.resolved";
pub const EV_TURN_USAGE: &str = "turn.usage";
pub const EV_DRIFT: &str = "drift";

/// **The** CHP event vocabulary — core + optional, live + reserved.
///
/// Pinned against `docs/CHP.md` by [`tests::the_doc_documents_every_event`], so
/// a new event cannot land in code without a wire description, nor in the doc
/// without an id L3 can gate on.
pub const EVENTS: &[Event] = &[
    // ── core (D4) ───────────────────────────────────────────────────────────
    ev(EV_HELLO, true, HELLO_ROUTE, true),
    ev(EV_PROMPT, true, "/context/retrieve", true),
    // LIVE since V35 Phase L. Claude reaches it through `Stop`
    // (`/claude/hook/stop`, § 4.5) and the reader
    // (`harness/claude/read.rs::assistant_texts`) is arbitrated off for a tab
    // that serves it. OpenCode declares `cannot` and keeps its SSE reader —
    // see `docs/CHP.md` § 4.6 for why, which is a real Phase L outcome under
    // design D6 and not an unfinished migration.
    ev(EV_ASSISTANT_TEXT, true, "/session/assistant_text", true),
    ev(EV_SESSION_END, true, "/session/end", false),
    // ── optional, live today ────────────────────────────────────────────────
    ev(EV_CONTEXT_COMPACTION, false, "/context/compaction", true),
    ev(EV_CONTEXT_SHOULD_READ, false, "/context/should_read", true),
    ev(EV_CONTEXT_POST_EDIT, false, "/context/post_edit", true),
    ev(EV_MEMORY_EVENT, false, "/memory/event", true),
    ev(EV_PERMISSION_EVENT, false, "/permission/event", true),
    ev(EV_TAINT_BEACON, false, "/latch/beacon", true),
    ev(EV_TOOL_GATE, false, "/latch/state", true),
    ev(
        EV_CHECKPOINT_PRE_MUTATION,
        false,
        "/workbench/tool_checkpoint",
        true,
    ),
    ev(EV_CONTRACT_DRIFT, false, "/activity/contract_drift", true),
    // ── realized by V35 Phase L (design D2) ─────────────────────────────────
    //
    // `session.usage` stays RESERVED, permanently-until-upstream-changes: **no
    // Claude hook payload carries token counts** (the common set is
    // `session_id` / `transcript_path` / `cwd` / `permission_mode` /
    // `hook_event_name`, and `PostCompact` exposes no compaction metrics), so
    // there is nothing to push and `claude.transcript.usage` keeps tailing the
    // transcript. `session.context` likewise: the statusline payload has no
    // hook equivalent. Naming them here rather than deleting them is the point
    // — an absence with a stated reason, not a blank.
    ev(EV_SESSION_USAGE, false, "/session/usage", false),
    ev(EV_SESSION_TOOL_RESULT, false, "/session/tool_result", true),
    ev(EV_SESSION_SUBAGENT, false, "/session/subagent", true),
    ev(EV_SESSION_CONTEXT, false, "/session/context", false),
    // ── V40 Phase C: the neutral vocabulary (locked decision 30) ────────────
    //
    // Reserved: declared, documented, and not yet served. Each replaces a
    // harness-named signal core currently speaks (`ClaudeOutputStarted`,
    // `AgentsActiveChanged`) or a reading it currently derives from one
    // harness's payload shape.
    ev(
        EV_HARNESS_OUTPUT_STARTED,
        false,
        "/session/output_started",
        false,
    ),
    ev(
        EV_HARNESS_OUTPUT_STOPPED,
        false,
        "/session/output_stopped",
        false,
    ),
    ev(EV_SUBAGENTS_ACTIVE, false, "/session/subagents_active", false),
    // The neutral half of prompt detection: what a harness reports is an EDGE,
    // and which of its notification types or footers means one is its own
    // business (locked decision 21). `permission.event` above stays — it is the
    // legacy `--notify-hook` transport, a Claude payload posted verbatim.
    ev(EV_PERMISSION_DETECTED, false, "/permission/detected", false),
    ev(EV_PERMISSION_RESOLVED, false, "/permission/resolved", false),
    // Distinct from `session.usage`, which is the whole-session roll-up: this
    // is ONE turn, carrying the neutral quota-window / token-kind / origin
    // types Phase D introduces.
    ev(EV_TURN_USAGE, false, "/session/turn_usage", false),
    // Reader-reported contract drift, as a push rather than as an Activity row
    // core writes on the reader's behalf.
    ev(EV_DRIFT, false, "/activity/drift", false),
];

/// The CHP event a live push route carries, or `None` for a route that carries
/// none (the hello, a reserved route, a route that is not CHP at all).
///
/// Derived from [`EVENTS`] for the same reason [`is_push_route`] is: the quiet
/// detector below joins on event ids, and a second hand-kept route table is how
/// a new event ends up observed for staleness but invisible to arbitration.
pub fn event_for_route(route: &str) -> Option<&'static str> {
    EVENTS
        .iter()
        .find(|e| e.live && e.route != HELLO_ROUTE && e.route == route)
        .map(|e| e.id)
}

/// Whether `route` carries a CHP message that can be *attributed* — i.e. a
/// live, non-hello route whose body cImp defines end to end.
///
/// Derived from [`EVENTS`] rather than restated, so a new event is observed for
/// staleness by being added to the vocabulary and not by remembering a second
/// list. `/session/hello` is excluded because its own handler records a richer
/// fact than an observation.
pub fn is_push_route(route: &str) -> bool {
    EVENTS
        .iter()
        .any(|e| e.live && e.route != HELLO_ROUTE && e.route == route)
}

// ── who is expected to speak CHP ────────────────────────────────────────────

/// Whether cImp *generates a CHP-speaking artifact* for this harness — and so
/// whether an absent or old `chp` from it means **stale**.
///
/// `opencode` yes: `tabs::config::opencode_plugin_source` bakes [`CHP_VERSION`]
/// into every plugin it writes, so a POST carrying less than that came from a
/// file an older build wrote.
///
/// `claude` **yes, since V35 Phase J**. Its L1 used to be five stateless shim
/// binaries with nowhere to put a version, which is why Phase I answered `false`
/// here (locked decision 5, recorded rather than assumed). Phase J replaced them
/// with `type: "http"` hooks whose emitted entries carry `X-CIMP-Chp` —
/// substituted from [`CHP_VERSION`] at overlay generation, exactly as the
/// generated OpenCode plugin substitutes it — so a Claude tab is now a
/// spawn-baked artifact that states its version, and the same three staleness
/// arms apply to it.
///
/// **The day that flipped, every Claude tab open across the upgrade started
/// reporting `old_plugin`.** That is the intended reading, not a false positive:
/// such a tab really is running an overlay full of `cimp --context-hook` command
/// hooks that this build no longer generates, and *restart the tab* really is
/// the fix. It is the V32 "needs a FRESH TAB" trap being named at exactly the
/// moment it applies.
pub fn expects_chp(agent: &str) -> bool {
    // V40 Phase A: the registry answers it. It was a hard-coded disjunction, so
    // stale-artifact detection was silently OFF for any harness not named in it
    // — a new harness would have shipped with the mechanism disabled and no
    // diff saying so.
    crate::harness::HarnessId::from_id(agent)
        .and_then(|h| h.descriptor())
        .is_some_and(|d| d.expects_chp)
}

// ── the per-tab peer registry ───────────────────────────────────────────────

/// One `cannot` entry from a hello: a capability this harness will **not**
/// serve, and why (design D3). Recorded and displayed in Phase I; nothing gates
/// on it until Phase L.
#[derive(Debug, Clone, Default, PartialEq, Eq, serde::Serialize)]
pub struct Unable {
    pub id: String,
    pub why: String,
}

/// What cImp knows about one tab's harness-side artifact.
///
/// In-memory and non-durable for the same reason the latch registry is: it
/// describes a *live* plugin in a *live* tab, and an app restart ends every one
/// of them. **Bounded** the same way too — the only writer validates the tab id
/// against the user's configured AI tabs before it inserts, so the key space is
/// `configured AI tabs × 2 agents`, not "whatever a request body said".
#[derive(Debug, Clone, Default, PartialEq, Eq, serde::Serialize)]
pub struct Peer {
    /// `claude` / `opencode`, already normalized through `source_for_consumer`.
    pub agent: String,
    pub tab: String,
    /// The highest-authority `chp` seen from this tab: a hello's if one has
    /// arrived, otherwise the last routed POST's. [`PRE_CHP`] when the artifact
    /// predates Phase I.
    pub chp: u32,
    /// The harness version the hello declared. **Empty is the normal case in
    /// Phase I** — OpenCode exposes no version to a plugin at module scope, so
    /// its hello omits the field; Claude sends no hello at all yet. The
    /// comparison [`stale_for`] makes with it is implemented and tested, and its
    /// producer arrives with Phase J.
    pub harness_version: String,
    /// What this artifact says it will do (design D3). Recorded, displayed,
    /// **not gated on** in Phase I.
    pub serves: Vec<String>,
    pub cannot: Vec<Unable>,
    /// When the last hello landed. `0` = none has.
    pub hello_at_ms: u64,
    /// When anything was last heard from this tab.
    pub seen_at_ms: u64,
    /// V35 Phase L — the quiet detector's counters: for each served capability
    /// that has a [`witness_of`] entry, how many WITNESS pushes have arrived
    /// since that capability last pushed (or since the hello).
    ///
    /// Reset wholesale by a hello, which is right: a hello is a fresh
    /// declaration from a (re)loaded artifact, so counting against the previous
    /// one would report the old artifact's silence as the new one's.
    #[serde(skip)]
    pub quiet_counters: BTreeMap<String, u32>,
    /// Capabilities already reported quiet for this artifact — the once-per-
    /// (tab, capability) latch, so a permanently dead hook costs one report and
    /// not one per turn. `Doubling` is the loopback's ledger for repeats; this
    /// is the cheaper "say it once" the ledger sits behind.
    #[serde(skip)]
    pub quiet_reported: BTreeSet<String>,
}

impl Peer {
    /// Whether a hello has ever arrived from this tab.
    pub fn greeted(&self) -> bool {
        self.hello_at_ms > 0
    }
}

/// The process-wide peer registry. See [`Peer`] for the bound.
fn peers() -> &'static Mutex<HashMap<(String, String), Peer>> {
    static PEERS: OnceLock<Mutex<HashMap<(String, String), Peer>>> = OnceLock::new();
    PEERS.get_or_init(Default::default)
}

fn lock() -> std::sync::MutexGuard<'static, HashMap<(String, String), Peer>> {
    peers().lock().unwrap_or_else(PoisonError::into_inner)
}

/// Whether this exact `(agent, tab, chp)` has already been recorded.
///
/// The cheap pre-check on the hot path: every prompt, every tool call and every
/// gate query carries a `chp`, and the *second* one from a tab says nothing new.
/// Its caller uses this to decide whether the observation is worth a settings
/// read (which is what validates the tab id), so the steady state costs one map
/// lookup per POST rather than one `Settings` clone per POST.
pub fn already_seen(agent: &str, tab: &str, chp: u32) -> bool {
    lock()
        .get(&(agent.to_string(), tab.to_string()))
        .is_some_and(|p| p.chp == chp)
}

/// Record a `chp` observed on a routed POST from a **validated** tab.
///
/// A hello outranks a routed POST for the same tab: the hello is the artifact's
/// own declaration and carries the version and the capability lists, so a bare
/// observation never overwrites it downwards — but a *changed* value does, since
/// that is the tab having been relaunched with a different artifact.
pub fn note_push(agent: &str, tab: &str, chp: u32, at_ms: u64) {
    let mut peers = lock();
    let e = peers
        .entry((agent.to_string(), tab.to_string()))
        .or_default();
    if e.agent.is_empty() {
        e.agent = agent.to_string();
        e.tab = tab.to_string();
    }
    if e.chp != chp {
        // The artifact changed under us — drop the hello's claims rather than
        // keep attributing them to a file that no longer says them.
        if e.greeted() {
            e.hello_at_ms = 0;
            e.serves.clear();
            e.cannot.clear();
            e.harness_version.clear();
        }
        // V35 Phase L: the quiet counters belong to the declaration they were
        // opened against. A different artifact makes them meaningless, and
        // keeping them would report the previous plugin's silence as this one's.
        e.quiet_counters.clear();
        e.quiet_reported.clear();
        e.chp = chp;
    }
    e.seen_at_ms = at_ms;
}

/// Record a `/session/hello` from a **validated** tab. Returns `true` when this
/// changed what cImp knows — which is what the handler keys its Activity row on,
/// so a re-hello identical to the stored one writes nothing.
#[allow(clippy::too_many_arguments)]
pub fn note_hello(
    agent: &str,
    tab: &str,
    chp: u32,
    harness_version: &str,
    serves: Vec<String>,
    cannot: Vec<Unable>,
    at_ms: u64,
) -> bool {
    let next = Peer {
        agent: agent.to_string(),
        tab: tab.to_string(),
        chp,
        harness_version: harness_version.to_string(),
        serves,
        cannot,
        hello_at_ms: at_ms,
        seen_at_ms: at_ms,
        ..Default::default()
    };
    let mut peers = lock();
    let key = (agent.to_string(), tab.to_string());
    let changed = match peers.get(&key) {
        // Timestamps are not part of the comparison: a plugin that re-hellos
        // unchanged must not be able to write a row per hello.
        Some(prev) => {
            prev.chp != next.chp
                || prev.harness_version != next.harness_version
                || prev.serves != next.serves
                || prev.cannot != next.cannot
                || !prev.greeted()
        }
        None => true,
    };
    peers.insert(key, next);
    changed
}

// ── V35 Phase L: arbitration — push wins WHEN SERVED ────────────────────────

/// **The arbitration rule, spelled once**: is `event` being pushed for this
/// exact `(agent, tab)`?
///
/// `true` ⇒ the fallback reader's output for THAT capability on THAT tab is
/// suppressed. `false` ⇒ the reader serves it, exactly as it did before Phase L.
/// Three properties, and each one closes a specific way this could go wrong:
///
/// * **Per capability.** A tab that pushes assistant text still has its
///   transcript tailed for usage and identity, which no hook payload carries
///   (see [`EVENTS`]). Suppressing a whole reader because one of its five taps
///   migrated is how a migration loses data.
/// * **Per tab.** Two Claude tabs can be running two different spawn-baked
///   overlays; one may push and the other (launched before the upgrade) may
///   not. A process-wide switch would mute the older tab entirely.
/// * **Only when the tab has actually spoken.** `greeted()` is required, not
///   just a non-empty `serves`: the declaration arrives *over the push path*,
///   so a hello is itself the proof that the path works. A pre-upgrade tab
///   sends none, gets `false` here, and behaves exactly as it did on `develop`
///   — which is what makes the migration safe to ship with old tabs open.
///
/// It is deliberately NOT "the capability is wired in settings": settings say
/// what cImp *asked* for; the hello says what the artifact on disk actually
/// does, and those two differ for precisely as long as a stale tab stays open
/// (§ 6.1).
pub fn served(agent: &str, tab: &str, event: &str) -> bool {
    lock()
        .get(&(agent.to_string(), tab.to_string()))
        .is_some_and(|p| p.greeted() && p.serves.iter().any(|s| s == event))
}

/// How many WITNESS pushes may arrive with a served capability silent before
/// that silence is reported as drift.
///
/// Three, not one: a single turn can legitimately end without the witnessed
/// event (an interrupted turn, a `/clear`), and reporting on the first one
/// would train the reader to ignore the notice — the exact failure V16's
/// tripwire had and this milestone exists to avoid.
pub const QUIET_WITNESS_PUSHES: u32 = 3;

/// The event whose arrival PROVES a served capability should also have pushed
/// — the "demonstrably active" half of locked decision 7.
///
/// A witness is only sound when the implication is exact, so the list is short
/// and every entry states the implication:
///
/// * `assistant_text` ← `prompt`: every prompt a harness accepts ends in a
///   final assistant message, so a `UserPromptSubmit` with no `Stop` behind it
///   is the `Stop` hook having stopped firing.
/// * `session.tool_result` ← `context.post_edit`: the post-edit hook fires on
///   `Edit|Write|MultiEdit`, and the tool-result hook fires on the SAME event
///   with an all-tools matcher, so an edit that produced one and not the other
///   is the wider entry having gone.
///
/// `session.subagent` deliberately has **none**: a session may legitimately
/// launch no sub-agents, forever, so there is no arrival that proves one should
/// have been reported. Inventing a threshold there would manufacture false
/// reports, which is worse than the gap — the gap is at least declared here.
pub fn witness_of(event: &str) -> Option<&'static str> {
    match event {
        EV_ASSISTANT_TEXT => Some(EV_PROMPT),
        EV_SESSION_TOOL_RESULT => Some(EV_CONTEXT_POST_EDIT),
        _ => None,
    }
}

/// Record one push of `event` from `(agent, tab)` and return the served
/// capabilities that have just gone QUIET.
///
/// **Locked decision 7: a served capability going silent must NOT quietly fall
/// back to the reader.** Falling back would restore the data and hide the
/// breakage — which is the silent-drift class this whole milestone exists to
/// delete. So the reader stays suppressed while the hello's claim stands, and
/// the silence is *reported* instead: each returned id gets a
/// `drift.payload.v1` row, which the Advisor already consolidates per
/// capability.
///
/// **Never inserts.** A peer this process has not validated (§ the handler's
/// `is_configured_tab` check) has no entry, so an unknown tab cannot grow the
/// map here — the counters ride an entry the validated path created.
pub fn note_event(agent: &str, tab: &str, event: &str) -> Vec<String> {
    let mut peers = lock();
    let Some(peer) = peers.get_mut(&(agent.to_string(), tab.to_string())) else {
        return Vec::new();
    };
    if !peer.greeted() {
        return Vec::new();
    }
    // This capability just pushed: it is demonstrably alive, so its counter
    // goes back to zero — including after a report, so a hook that recovers
    // stops being counted against its own past silence.
    if peer.serves.iter().any(|s| s == event) {
        peer.quiet_counters.insert(event.to_string(), 0);
    }
    // …and every served capability WITNESSED by this event moves one step
    // closer to being reported.
    let mut quiet: Vec<String> = Vec::new();
    let watched: Vec<String> = peer
        .serves
        .iter()
        .filter(|s| witness_of(s) == Some(event) && s.as_str() != event)
        .cloned()
        .collect();
    for id in watched {
        let n = peer.quiet_counters.entry(id.clone()).or_insert(0);
        *n = n.saturating_add(1);
        if *n >= QUIET_WITNESS_PUSHES && peer.quiet_reported.insert(id.clone()) {
            quiet.push(id);
        }
    }
    quiet
}

/// Every peer cImp currently knows about, in a stable order.
pub fn snapshot() -> Vec<Peer> {
    let mut rows: Vec<Peer> = lock().values().cloned().collect();
    rows.sort_by(|a, b| (&a.agent, &a.tab).cmp(&(&b.agent, &b.tab)));
    rows
}

// ── the consumer: stale-artifact detection ──────────────────────────────────

/// Why an artifact is being reported as out of step. Machine tokens, because
/// the three cases want three different sentences and the panel must not
/// re-derive which is which from the numbers.
pub const STALE_OLD_PLUGIN: &str = "old_plugin";
pub const STALE_NEW_PLUGIN: &str = "new_plugin";
pub const STALE_VERSION: &str = "harness_version";

/// One tab whose harness-side artifact is out of step with this binary.
///
/// The V32 deploy trap, made legible: the four "needs a FRESH TAB" incidents
/// were all this, and all of them were diagnosed by a human eventually
/// remembering that plugins are spawn-baked.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
pub struct StalePlugin {
    pub tab: String,
    pub agent: String,
    /// The `chp` this tab's artifact actually sends. [`PRE_CHP`] = it sends none.
    pub seen_chp: u32,
    /// [`CHP_VERSION`] — what this binary writes into a freshly generated
    /// artifact.
    pub expected: u32,
    /// [`STALE_OLD_PLUGIN`] / [`STALE_NEW_PLUGIN`] / [`STALE_VERSION`].
    pub kind: &'static str,
    /// The sentence, written here rather than four times in a Svelte `{#if}`
    /// chain — the same rule `health::DegradationView::label` follows.
    pub note: String,
}

/// Classify one peer against this binary. `None` = in step.
///
/// Pure, so all three arms are assertable without touching the process-global
/// registry (the suite runs cases concurrently in one process).
fn classify(peer: &Peer, known_version: &str) -> Option<StalePlugin> {
    let row = |kind: &'static str, note: String| StalePlugin {
        tab: peer.tab.clone(),
        agent: peer.agent.clone(),
        seen_chp: peer.chp,
        expected: CHP_VERSION,
        kind,
        note,
    };
    // A HIGHER version than this binary knows is staleness too — the other way
    // round. An old binary is running beside a plugin a newer build wrote, which
    // is the same deploy trap seen from the downgrade side, and reading it as
    // "fine, it is at least current" would hide exactly that.
    if peer.chp > CHP_VERSION {
        return Some(row(
            STALE_NEW_PLUGIN,
            format!(
                "This tab's harness plugin speaks CHP {} — NEWER than this cImp build understands \
                 (CHP {CHP_VERSION}). The plugin was written by a newer build; this one is the \
                 stale side. Nothing is refused, but a capability the newer plugin assumes may \
                 not exist here.",
                peer.chp
            ),
        ));
    }
    if peer.chp < CHP_VERSION && expects_chp(&peer.agent) {
        let what = if peer.chp == PRE_CHP {
            "sends no `chp` field at all, so it predates CHP".to_string()
        } else {
            format!("speaks CHP {}", peer.chp)
        };
        return Some(row(
            STALE_OLD_PLUGIN,
            format!(
                "This tab's harness plugin {what} — this build writes CHP {CHP_VERSION}. The \
                 plugin file is baked at tab launch, so a tab started before the upgrade keeps \
                 the old one: RESTART THE TAB. Until then its behavior is the old build's, which \
                 is what has previously read as a mysterious failure rather than as a version \
                 mismatch."
            ),
        ));
    }
    if !peer.harness_version.is_empty()
        && !known_version.is_empty()
        && peer.harness_version != known_version
    {
        return Some(row(
            STALE_VERSION,
            format!(
                "This tab's plugin declared harness version {:?}, but the installed CLI is now \
                 {known_version:?}. The tab is running against a build cImp has not verified its \
                 contracts on — restart it, or re-run the checks.",
                peer.harness_version
            ),
        ));
    }
    None
}

/// Every out-of-step artifact for one harness, in a stable order.
///
/// `known_version` is that harness's currently-observed CLI version
/// (`harness_versions.<harness>_last_seen`); empty disables the version arm
/// rather than reporting every tab as mismatched against nothing.
pub fn stale_for(agent: &str, known_version: &str) -> Vec<StalePlugin> {
    let mut out: Vec<StalePlugin> = snapshot()
        .iter()
        .filter(|p| p.agent == agent)
        .filter_map(|p| classify(p, known_version))
        .collect();
    out.sort_by(|a, b| a.tab.cmp(&b.tab));
    out
}

// ── reading `chp` off a routed POST ─────────────────────────────────────────

/// The three fields any CHP message carries, read leniently off a body cImp
/// otherwise leaves to its route's own type.
///
/// Deliberately a *second*, tiny deserialization rather than a `chp` field added
/// to nine body structs: the routes' own types stay byte-identical (zero
/// behavior change is the phase's exit criterion), and the identity fields are
/// read here exactly as each route reads them — some spell the discriminator
/// `agent` and some `consumer`, which is a real fact about the wire and is
/// documented as such in `docs/CHP.md` rather than papered over.
#[derive(Debug, Clone, PartialEq, Eq, Default, serde::Deserialize)]
pub struct Envelope {
    /// Absent ⇒ [`PRE_CHP`]. **Never an error** — see [`PRE_CHP`].
    #[serde(default)]
    pub chp: Option<u32>,
    #[serde(default)]
    pub agent: Option<String>,
    #[serde(default)]
    pub consumer: Option<String>,
    #[serde(default)]
    pub tab: Option<String>,
}

impl Envelope {
    /// The discriminator this body carries, whichever of the two names it used.
    pub fn agent_token(&self) -> &str {
        self.agent
            .as_deref()
            .or(self.consumer.as_deref())
            .unwrap_or("")
    }
}

/// The CHP envelope of a routed POST, or `None` when there is nothing to
/// observe: a route that carries no CHP message, a body that is not JSON, or a
/// body with no tab identity to attribute the observation to.
///
/// A body that fails to parse is silently ignored, which is right for a *side*
/// observation — the route's own handler owns the 400, and an observation that
/// could reject a request would be a behavior change.
pub fn envelope(route: &str, body: &[u8]) -> Option<(Envelope, String)> {
    if !is_push_route(route) {
        return None;
    }
    let env: Envelope = serde_json::from_slice(body).ok()?;
    let tab = env.tab.as_deref().map(str::trim).filter(|t| !t.is_empty())?;
    let tab = tab.to_string();
    Some((env, tab))
}

#[cfg(test)]
pub(crate) fn note_for_test(peer: Peer) {
    lock().insert((peer.agent.clone(), peer.tab.clone()), peer);
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `docs/CHP.md` is the written schema; this file is the version. The two
    /// are one commit or neither — same `include_str!` idiom as
    /// `contract::tests::matrix_matches_maintenance_doc`.
    const CHP_MD: &str = include_str!("../../../docs/CHP.md");

    #[test]
    fn the_doc_states_this_version() {
        let needle = format!("**Protocol version:** `chp = {CHP_VERSION}`");
        assert!(
            CHP_MD.contains(&needle),
            "docs/CHP.md must state the protocol version its schema describes, exactly as \
             `{needle}` — `CHP_VERSION` is {CHP_VERSION} and the doc does not say so"
        );
        // …and it must not ALSO claim a different one, which is what a
        // half-finished bump looks like.
        for other in 0..(CHP_VERSION + 3) {
            if other == CHP_VERSION {
                continue;
            }
            assert!(
                !CHP_MD.contains(&format!("**Protocol version:** `chp = {other}`")),
                "docs/CHP.md states two protocol versions"
            );
        }
    }

    /// Every event id in the vocabulary is described in the doc, and the doc
    /// names no id the code does not have. The event set is what L3 gates
    /// against from Phase L on, so an id that exists in only one of the two is a
    /// capability nobody can reason about.
    #[test]
    fn the_doc_documents_every_event() {
        for e in EVENTS {
            assert!(
                CHP_MD.contains(&format!("`{}`", e.id)),
                "CHP event `{}` is in the code vocabulary but not in docs/CHP.md",
                e.id
            );
            // Route needles end at the closing backtick, so both spellings the
            // doc uses match: bare (`` `/session/hello` ``) and method-prefixed
            // (`` `POST /session/hello` ``).
            assert!(
                CHP_MD.contains(&format!("{}`", e.route)),
                "CHP event `{}`'s route `{}` is not documented in docs/CHP.md",
                e.id,
                e.route
            );
        }
        // Ids are the join key; duplicates would make the table ambiguous.
        let mut ids: Vec<&str> = EVENTS.iter().map(|e| e.id).collect();
        ids.sort_unstable();
        let n = ids.len();
        ids.dedup();
        assert_eq!(n, ids.len(), "a CHP event id is declared twice");
        // A core event that is not live is a declared prerequisite nothing
        // serves — allowed (Phase L adds two), but it must be visible in the
        // table rather than implied.
        assert!(
            EVENTS.iter().any(|e| e.core && e.live),
            "no core event is live — the vocabulary is vacuous"
        );
    }

    /// The push-route predicate is derived from the vocabulary, and `hello` is
    /// deliberately not one: its handler records more than an observation can.
    #[test]
    fn push_routes_come_from_the_vocabulary() {
        assert!(is_push_route("/context/retrieve"));
        assert!(is_push_route("/latch/beacon"));
        assert!(is_push_route("/workbench/tool_checkpoint"));
        assert!(!is_push_route(HELLO_ROUTE));
        // Reserved (Phase L) routes are not observed yet — nothing posts to them.
        assert!(!is_push_route("/session/usage"));
        // And a route that is not CHP at all.
        assert!(!is_push_route("/mcp/call"));
        assert!(!is_push_route("/activity/discovery_skipped"));
    }

    /// The envelope reads `chp` off a body whose own type knows nothing about
    /// it, tolerates its absence, and accepts either spelling of the
    /// discriminator — because the live wire genuinely uses both.
    #[test]
    fn the_envelope_is_lenient_in_every_direction() {
        // A full modern body.
        let (env, tab) = envelope(
            "/context/retrieve",
            br#"{"chp":1,"cwd":"p","prompt":"hi","session_id":"s","agent":"opencode","tab":"oc-1"}"#,
        )
        .expect("a CHP body");
        assert_eq!(env.chp, Some(1));
        assert_eq!(env.agent_token(), "opencode");
        assert_eq!(tab, "oc-1");

        // A pre-CHP body — the tolerated-absent path, which must not error.
        let (env, tab) = envelope(
            "/context/retrieve",
            br#"{"cwd":"p","prompt":"hi","session_id":"s","agent":"claude","tab":"claude-1"}"#,
        )
        .expect("a pre-CHP body is still a CHP body");
        assert_eq!(env.chp, None);
        assert_eq!(env.chp.unwrap_or(PRE_CHP), PRE_CHP);
        assert_eq!(tab, "claude-1");

        // `consumer` is the other spelling, used by /latch/*.
        let (env, _) = envelope("/latch/state", br#"{"chp":1,"tab":"oc-2","consumer":"opencode"}"#)
            .expect("a latch body");
        assert_eq!(env.agent_token(), "opencode");

        // No tab ⇒ nothing to attribute ⇒ no observation. `/activity/contract_drift`
        // is the standing example: it carries no tab at all.
        assert!(envelope("/activity/contract_drift", br#"{"shim":"read_hook"}"#).is_none());
        assert!(envelope("/context/retrieve", br#"{"tab":"  "}"#).is_none());
        // Malformed JSON is ignored, never rejected — the route's own handler
        // owns the 400.
        assert!(envelope("/context/retrieve", b"not json").is_none());
        // A non-CHP route is never observed even with a perfect body.
        assert!(envelope("/mcp/call", br#"{"chp":1,"tab":"oc-1"}"#).is_none());
    }

    fn peer(agent: &str, chp: u32) -> Peer {
        Peer {
            agent: agent.to_string(),
            tab: "t".to_string(),
            chp,
            ..Default::default()
        }
    }

    /// The three staleness arms, and the two silences that matter more.
    #[test]
    fn staleness_classifies_old_new_and_version_drift() {
        // In step: nothing.
        assert!(classify(&peer("opencode", CHP_VERSION), "1.18.13").is_none());

        // OLDER — the V32 "needs a FRESH TAB" trap, now named.
        let old = classify(&peer("opencode", PRE_CHP), "").expect("a pre-CHP plugin is stale");
        assert_eq!(old.kind, STALE_OLD_PLUGIN);
        assert_eq!(old.seen_chp, PRE_CHP);
        assert_eq!(old.expected, CHP_VERSION);
        assert!(old.note.contains("RESTART THE TAB"));

        // NEWER — old binary, new plugin. Same trap, other side.
        let new = classify(&peer("opencode", CHP_VERSION + 1), "").expect("a newer plugin is stale");
        assert_eq!(new.kind, STALE_NEW_PLUGIN);
        assert!(new.note.contains("NEWER"));

        // CLAUDE, since V35 Phase J: its overlay is a spawn-baked artifact that
        // states its `chp` in a header, so a tab that sends none is a tab still
        // running the pre-Phase-J command hooks — the V32 "needs a FRESH TAB"
        // trap, named at the moment it applies. In Phase I this asserted the
        // opposite (`is_none`), deliberately, because there was nothing on the
        // Claude side that could carry a version.
        let claude = classify(&peer("claude", PRE_CHP), "2.1.232")
            .expect("a pre-Phase-J Claude overlay is stale");
        assert_eq!(claude.kind, STALE_OLD_PLUGIN);
        assert!(claude.note.contains("RESTART THE TAB"));
        assert!(classify(&peer("claude", CHP_VERSION), "2.1.232").is_none());
        assert!(expects_chp("claude") && expects_chp("opencode"));
        assert!(!expects_chp("codex"), "an unknown harness ships no artifact");

        // Version drift, when a hello declares one at all.
        let mut greeted = peer("opencode", CHP_VERSION);
        greeted.harness_version = "1.18.13".to_string();
        greeted.hello_at_ms = 7;
        assert!(classify(&greeted, "1.18.13").is_none());
        let drift = classify(&greeted, "1.19.0").expect("a version mismatch is stale");
        assert_eq!(drift.kind, STALE_VERSION);
        // …and an unknown current version disables the arm rather than firing
        // it against nothing.
        assert!(classify(&greeted, "").is_none());
    }

    /// A hello that says the same thing twice writes nothing the second time —
    /// the property the Activity row is keyed on, so a plugin re-loading cannot
    /// flood the feed.
    #[test]
    fn a_repeated_hello_is_not_a_change() {
        let tab = "chp-repeat-test";
        let serves = vec![EV_PROMPT.to_string()];
        let now = 100;
        assert!(
            note_hello("opencode", tab, CHP_VERSION, "", serves.clone(), vec![], now),
            "the first hello is always a change"
        );
        assert!(
            !note_hello("opencode", tab, CHP_VERSION, "", serves.clone(), vec![], now + 1),
            "an identical hello is not"
        );
        assert!(
            note_hello(
                "opencode",
                tab,
                CHP_VERSION,
                "",
                vec![EV_PROMPT.to_string(), EV_TOOL_GATE.to_string()],
                vec![],
                now + 2
            ),
            "a different `serves` list is"
        );
    }

    // ── V35 Phase L: arbitration ────────────────────────────────────────────

    /// **The rule, and the mid-session switchover.**
    ///
    /// The two dangerous failures this phase could ship are TTS speaking one
    /// message twice and one tool result being counted twice, and both reduce
    /// to the same question: can the reader's tap and the push core ever both
    /// act on one datum? They cannot, because they ask ONE predicate — so this
    /// test is about that predicate, in the three states a tab passes through.
    #[test]
    fn arbitration_is_per_capability_per_tab_and_needs_a_hello() {
        let tab = "chp-arbitration-test";
        let other = "chp-arbitration-other-tab";

        // STATE 1 — a pre-upgrade tab: no hello, so nothing is served and the
        // reader does everything, exactly as it did before this phase. This is
        // the assertion that makes the migration safe to ship with tabs open.
        assert!(!served("claude", tab, EV_ASSISTANT_TEXT));
        note_push("claude", tab, PRE_CHP, 10);
        assert!(
            !served("claude", tab, EV_ASSISTANT_TEXT),
            "a routed POST is not a declaration — only a hello can move arbitration"
        );

        // STATE 2 — the hello lands MID-SESSION (`SessionStart` fires on resume
        // and clear, not only at launch). From here the reader's tap for the
        // declared capabilities is suppressed and the push core acts.
        note_hello(
            "claude",
            tab,
            CHP_VERSION,
            "",
            vec![
                EV_ASSISTANT_TEXT.to_string(),
                EV_SESSION_TOOL_RESULT.to_string(),
            ],
            vec![],
            20,
        );
        assert!(served("claude", tab, EV_ASSISTANT_TEXT));
        assert!(served("claude", tab, EV_SESSION_TOOL_RESULT));
        // PER CAPABILITY: an undeclared one is still the reader's. Usage is the
        // standing example — no hook payload carries token counts, so the
        // transcript tail must keep reading it on a tab that pushes prose.
        assert!(
            !served("claude", tab, EV_SESSION_USAGE),
            "a tab that pushes prose still has its transcript tailed for usage"
        );
        assert!(!served("claude", tab, EV_SESSION_SUBAGENT));
        // PER TAB: a sibling tab running an older spawn-baked overlay is
        // untouched. A process-wide switch would have muted it.
        assert!(!served("claude", other, EV_ASSISTANT_TEXT));
        // PER AGENT: OpenCode declares `cannot` for the read path, so its
        // reader keeps serving even while a Claude tab pushes.
        assert!(!served("opencode", tab, EV_ASSISTANT_TEXT));

        // STATE 3 — the tab is relaunched with an older artifact. The hello's
        // claims are retired, so arbitration hands the capability straight back
        // to the reader rather than leaving a tab served by nobody.
        note_push("claude", tab, PRE_CHP, 30);
        assert!(
            !served("claude", tab, EV_ASSISTANT_TEXT),
            "a retired hello must not keep a reader suppressed — that is a mute tab"
        );
    }

    /// **A served capability that goes quiet is REPORTED, not un-served**
    /// (locked decision 7).
    ///
    /// The tempting alternative — notice the silence and quietly resume the
    /// reader — restores the data and hides the breakage, which is the exact
    /// class of silent drift this milestone exists to delete. So the counters
    /// produce a report and change nothing about arbitration.
    #[test]
    fn a_served_capability_going_quiet_is_reported_once_and_changes_nothing() {
        let tab = "chp-quiet-test";
        note_hello(
            "claude",
            tab,
            CHP_VERSION,
            "",
            vec![EV_ASSISTANT_TEXT.to_string()],
            vec![],
            10,
        );
        // Witness pushes below the threshold say nothing: one turn can end
        // without its `Stop` (an interruption, a `/clear`), and reporting on the
        // first would train the reader to ignore the notice.
        for _ in 1..QUIET_WITNESS_PUSHES {
            assert!(note_event("claude", tab, EV_PROMPT).is_empty());
        }
        assert_eq!(
            note_event("claude", tab, EV_PROMPT),
            vec![EV_ASSISTANT_TEXT.to_string()],
            "three prompts with no Stop between them is the hook having stopped firing"
        );
        // ONCE. A permanently dead hook costs one report, not one per turn.
        for _ in 0..10 {
            assert!(note_event("claude", tab, EV_PROMPT).is_empty());
        }
        // …and the reader stays suppressed throughout: the report is the whole
        // response to the silence.
        assert!(served("claude", tab, EV_ASSISTANT_TEXT));

        // A capability that IS pushing resets its own counter, so a hook that
        // recovers stops being counted against its past silence.
        let tab = "chp-quiet-recovery-test";
        note_hello(
            "claude",
            tab,
            CHP_VERSION,
            "",
            vec![EV_ASSISTANT_TEXT.to_string()],
            vec![],
            10,
        );
        for _ in 0..20 {
            assert!(note_event("claude", tab, EV_PROMPT).is_empty());
            assert!(note_event("claude", tab, EV_ASSISTANT_TEXT).is_empty());
        }

        // A capability the tab does NOT serve is never reported quiet — there is
        // nothing to be silent about.
        let tab = "chp-quiet-unserved-test";
        note_hello("claude", tab, CHP_VERSION, "", vec![], vec![], 10);
        for _ in 0..20 {
            assert!(note_event("claude", tab, EV_PROMPT).is_empty());
        }
        // Neither is an unknown tab: the counters never INSERT, so an
        // unvalidated caller cannot grow the registry through this path.
        assert!(note_event("claude", "chp-quiet-never-seen", EV_PROMPT).is_empty());
        assert!(!snapshot().iter().any(|p| p.tab == "chp-quiet-never-seen"));
    }

    /// The witness table is sound in the only direction that matters: every
    /// witness is itself a live CHP event, and no capability witnesses itself.
    ///
    /// `session.subagent` having NO witness is asserted, not tolerated — a
    /// session may legitimately launch no sub-agents forever, so any threshold
    /// there would manufacture false reports.
    #[test]
    fn every_witness_is_a_live_event_and_nothing_witnesses_itself() {
        for e in EVENTS {
            let Some(w) = witness_of(e.id) else { continue };
            assert_ne!(w, e.id, "`{}` cannot witness itself", e.id);
            let witness = EVENTS
                .iter()
                .find(|x| x.id == w)
                .unwrap_or_else(|| panic!("`{}`'s witness `{w}` is not a CHP event", e.id));
            assert!(
                witness.live,
                "`{}`'s witness `{w}` is reserved — a witness that never arrives can never fire",
                e.id
            );
        }
        assert!(
            witness_of(EV_SESSION_SUBAGENT).is_none(),
            "a session may launch no sub-agents; a threshold here would be a false-report machine"
        );
        assert_eq!(witness_of(EV_ASSISTANT_TEXT), Some(EV_PROMPT));
        assert_eq!(witness_of(EV_SESSION_TOOL_RESULT), Some(EV_CONTEXT_POST_EDIT));
    }

    /// **Both sides ask this module, and neither reimplements the decision.**
    ///
    /// The double-speak and double-count failures are only impossible while
    /// that is true — a reader tap guarded by its own boolean, or a push core
    /// that acts unconditionally, would restore them without any test noticing.
    /// So this is a source scan, in the same idiom as
    /// [`crate::harness::layering`]: for each migrated capability, the reader
    /// that used to own it must consult the predicate, and the core that now
    /// owns it must consult the same one.
    #[test]
    fn each_migrated_capability_is_arbitrated_on_both_sides() {
        const READER: &str = include_str!("claude/read.rs");
        const LOOPBACK: &str = include_str!("../offload/loopback.rs");
        // (event const name, how the reader spells its guard)
        for (event, konst) in [
            (EV_ASSISTANT_TEXT, "EV_ASSISTANT_TEXT"),
            (EV_SESSION_TOOL_RESULT, "EV_SESSION_TOOL_RESULT"),
            (EV_SESSION_SUBAGENT, "EV_SESSION_SUBAGENT"),
        ] {
            assert!(
                READER.contains(&format!("ctx.pushed(\"claude\", crate::harness::chp::{konst})")),
                "`{event}` migrated but `harness/claude/read.rs` still produces it \
                 unconditionally — that is the double-delivery this phase exists to avoid"
            );
            assert!(
                LOOPBACK.contains(&format!("crate::harness::chp::served(agent, tab, crate::harness::chp::{konst})")),
                "`{event}`'s push core does not check `chp::served` — it would act on a tab whose \
                 reader is also still producing it"
            );
        }
    }

    /// A routed POST carrying a different `chp` than the stored hello means the
    /// tab was relaunched with a different artifact — the hello's claims are
    /// dropped rather than kept attributed to a file that no longer makes them.
    #[test]
    fn a_changed_chp_retires_the_stored_hello() {
        let tab = "chp-relaunch-test";
        note_hello(
            "opencode",
            tab,
            CHP_VERSION,
            "1.18.13",
            vec![EV_TOOL_GATE.to_string()],
            vec![Unable {
                id: EV_TAINT_BEACON.to_string(),
                why: "off".to_string(),
            }],
            10,
        );
        assert!(already_seen("opencode", tab, CHP_VERSION));
        note_push("opencode", tab, PRE_CHP, 20);
        let p = snapshot()
            .into_iter()
            .find(|p| p.tab == tab)
            .expect("the peer survives");
        assert_eq!(p.chp, PRE_CHP);
        assert!(!p.greeted(), "the stale hello must not outlive its artifact");
        assert!(p.serves.is_empty() && p.cannot.is_empty() && p.harness_version.is_empty());
        // …and the same value again is a no-op the hot path can skip.
        assert!(already_seen("opencode", tab, PRE_CHP));
        assert!(!already_seen("opencode", tab, CHP_VERSION));
    }
}
