// Generated by cImp (V10 Code Intelligence). Do not edit — regenerated each launch.

// ── V33 (C6, H-7's cheap half): the ONE `fetch` this file will ever use ─────
//
// Bound HERE, once, while this module is being evaluated — not resolved out of
// `globalThis` inside the handlers on every call, which is what it used to do.
//
// WHY. cImp runs OpenCode ADDITIVELY: it does not set
// `OPENCODE_DISABLE_PROJECT_CONFIG`, so a cloned repo's own `opencode.json`
// merges underneath cImp's pins, and its `plugin` key is NOT one of the pinned
// ones. A plugin is arbitrary in-process code, and the cheapest thing such a
// module can do is assign `globalThis.fetch`. Against a late-resolving call
// site that one line disarmed BOTH halves of `tool.execute.before` at once —
// the Phase H gate never reaches /latch/state (its own fail-open contract then
// refuses nothing) and the Phase F beacon never reaches /latch/beacon (nothing
// is ever latched) — while cImp's /status and the Settings badge went on
// reporting both ON. A control that reports ON while doing nothing is worse
// than one that is off.
//
// WHAT THIS IS AND IS NOT. It is a NARROWING, not containment, and its bound is
// LOAD ORDER: a hostile module that is EVALUATED BEFORE this one still gets its
// swap in first and is captured here instead. Nothing in an in-process JS hook
// is a security boundary — see the honest-limits block below, which applies to
// this line too. What it closes is the zero-effort variant, where a swap
// performed at ANY point after startup (in a handler, on a timer, on the first
// tool call) silently disarmed a control that was already running.
//
// `.bind(globalThis)`: a bare `const f = globalThis.fetch` throws "Illegal
// invocation" in runtimes whose `fetch` requires its receiver. The `typeof`
// guard covers the other direction — in a runtime with no `fetch` at all this
// file must be INERT, not throw at load: a module that throws while loading
// takes the harness's whole plugin load down with it, and every call site below
// already treats a rejected fetch as "unreported", never as "refused".
const CIMP_FETCH =
  typeof globalThis.fetch === "function"
    ? globalThis.fetch.bind(globalThis)
    : () => Promise.reject(new Error("cimp: this runtime has no fetch"));

const CIMP_LOOPBACK = "http://127.0.0.1:54321";
const CIMP_TOKEN = "deadbeef00";
// ── V35 Phase I: CHP, the cImp Harness Protocol ─────────────────────────────
//
// The version of the loopback wire this FILE speaks, substituted from
// `harness::chp::CHP_VERSION` at generation time — never typed here as a
// literal, so the constant has exactly one definition and `docs/CHP.md` is
// test-pinned to it.
//
// WHY IT IS ON THE WIRE. This file is written to disk at TAB LAUNCH and outlives
// the binary that wrote it: upgrade cImp with a tab still open and an old plugin
// is talking to new loopback code. V32 recorded that as a deploy trap four
// separate times, always with the same mitigation — "needs a FRESH TAB or it
// reads as a failure". With this field the app RECOGNISES the mismatch and says
// so in Settings → Harness health, instead of the user meeting it as a
// capability that quietly misbehaves.
//
// It is ADDITIVE and TOLERATED-ABSENT in both directions: an app that predates
// CHP ignores the field, and an app that postdates it treats a body without one
// as pre-CHP. Nothing is ever refused over a version.
const CIMP_CHP = 2;
const CIMP_INJECT_ENABLED = true;
const CIMP_AUTO_CHECK_ENABLED = true;
const CIMP_EDIT_TOOLS = new Set(["edit", "write", "patch"]);
// V32 Phase F (locked decision 14): report-only visibility of OpenCode's OWN
// web tools, which never route through cImp and are therefore invisible to the
// proxy's taint latch. `false` in `off`/`deny` mode — in `deny` the pinned
// `agent.build.permission` block refuses them outright, so there is nothing to
// observe.
const CIMP_BEACON_ENABLED = true;
const CIMP_WEB_TOOLS = new Set(["webfetch","websearch"]);
// ── V33 Phase F: the pre-mutation CHECKPOINT ────────────────────────────────
//
// A Workbench checkpoint taken immediately before a native tool that can
// change files on disk, attributed to that exact call. The Timeline can then
// blame the call and rewind to just before it, instead of to the start of a
// turn that contains a dozen edits.
//
// The set is `toolclass::OPENCODE_NATIVE_TABLE`'s `mutates_fs` column,
// rendered — the same reviewed table the gate's sets come from, so the JS and
// Rust cannot drift about which tools write. It is NOT the local-capability
// set: `read`/`glob`/`grep` are local capability and change nothing, and
// checkpointing before each of them would be a `git add -A` per file read.
//
// The app re-checks the name against that same table, so this set only decides
// what costs a round trip. Report-only: the POST is awaited (the ordering IS
// the feature, and unlike the Claude hook this one can wait safely) but every
// failure is swallowed — a lost checkpoint costs one call its rewind point, a
// thrown error would refuse the user's own edit.
const CIMP_CHECKPOINT_ENABLED = true;
const CIMP_MUTATING_TOOLS = new Set(["bash","edit","write","patch","apply_patch","execute"]);
// The cImp TAB this FILE was generated for, baked at spawn. The tab id is the
// key the whole latch registry uses, and the hook input carries no tab or cwd
// identity (the E2 spike's finding), so without it a beacon has nothing to
// engage.
const CIMP_TAB_ID = "opencode";
// …and whether this OpenCode process is that tab's, from the env
// (`compose_ai_env` sets `CIMP_TAB_ID` on every OpenCode spawn).
//
// #48 (H-2): there is now ONE FILE PER TAB in `.opencode/plugin/`, because the
// flags baked above are resolved per tab while the directory is shared by every
// builtin tab. OpenCode loads EVERY file in that directory into EVERY session
// it starts there — so a file that is not this process's tab must be completely
// inert, or tab B's flags would run under tab A's identity and every handler
// would fire once per installed file. Every handler below returns immediately
// unless this matches.
//
// A hand-run `opencode` in the same project (no `CIMP_TAB_ID` in its env) now
// matches nothing and gets no injection, no memory tap and no beacon. That is
// deliberate: those POSTs carried a session cImp has no tab for, and the
// alternative — letting an unbound process run every installed file — is
// duplicate prompt injection and duplicate usage rows.
const CIMP_TAB_MATCH =
  (typeof process !== "undefined" && process.env && process.env.CIMP_TAB_ID) === CIMP_TAB_ID;

// ── V32 Phase H (locked decision 17): the native-tool GATE ──────────────────
//
// Beaconing tells cImp a native web tool ran. Gating additionally REFUSES the
// harness's own tools on the far side of this tab's taint latch: under an
// EXTERNAL latch every local-capability native, under a LOCAL latch the web
// ones. Default off; this flag is baked at tab spawn.
//
// WHOLE-SURFACE OR NOTHING. The E2 spike watched the model route a blocked
// `write` through `bash`, so the local set below is the complete
// local-capability surface of the registry, `apply_patch` included (it REPLACES
// edit/write on OpenAI-provider models). `task` is deliberately absent: a
// sub-agent's own tool calls fire this same hook with this same CIMP_TAB_ID, so
// its `bash`/`read` are gated at the same latch — gating the spawn itself would
// refuse an orchestration primitive whose dangerous leaves are already closed.
//
// HONEST LIMIT — this is POLICY, NOT CONTAINMENT. It runs inside the agent's
// own process: `OPENCODE_PURE=1` and spawning a second, ungated `opencode` walk
// around it, a user-typed `!shell` and the raw PTY never reach a plugin hook at
// all, and `bash` stays egress-capable by nature. OS-level containment is V33.
//
// THE STATE TABLE (#48, F-13). Local-capability natives are refused iff the
// latch is EXTERNAL (or a beacon of this tab's is still in flight). The web
// natives are refused unless this tab is either demonstrably CLEAN (`open` and
// uncontaminated) or in research mode (`external`, where local capability is
// withheld at the same instant):
//
//   latch=open   contaminated=false  → local: admit  web: admit
//   latch=open   contaminated=true   → local: admit  web: REFUSE
//   latch=local  (either)            → local: admit  web: refuse
//   latch=external                   → local: REFUSE web: admit
//
// #48 (F-23): the `latch=local` row refuses the same call whichever way the tab
// got there, but it does not say the same thing. Reached by a local-capability
// tool it blames that tool; reached by the user's decision-15 flip it says so
// instead, because blaming a tool call that never ran is a confident, wrong
// causal story about a security event. The selector is `local_by_user_flip` from
// `/latch/state` — a fact the app recorded when it applied the override.
//
// `latch=open, contaminated=true` is the row F-13 named, and it is not exotic:
// a session rotation reopens the latch and deliberately keeps the bit (H-2), and
// `bash` is pinned `allow`, so a contaminated tab could spawn a second
// `opencode` that inherits CIMP_TAB_ID, publish a fresh session id under this
// tab's identity, and get its web tools back. The bit is what survives that.
const CIMP_NATIVE_GATE_ENABLED = true;
const CIMP_NATIVE_LOCAL_TOOLS = new Set(["bash","read","glob","grep","edit","write","patch","apply_patch","execute","lsp"]);
const CIMP_REFUSAL_NATIVE_LOCAL = "REFUSED (security boundary): this session has already used an external tool (web fetch/search or an MCP-server tool), so this harness's own local tools — file reads, edits, patches, file search and shell commands — are unavailable for the remainder of this session. This cannot be unlocked, re-asked for, or worked around; it is enforced outside the model, and spawning a sub-agent or a nested shell reaches the same boundary. Continue with the tools you still have, or answer with what you have gathered.";
const CIMP_REFUSAL_NATIVE_WEB = "REFUSED (security boundary): this session has already used a local-capability tool (file read, edit, file search or shell command), so this harness's own web tools — fetch and search — are unavailable for the remainder of this session. This cannot be unlocked, re-asked for, or worked around; it is enforced outside the model, and spawning a sub-agent reaches the same boundary. Continue with the tools you still have, or answer with what you have gathered.";
// #48 (F-13): the THIRD refusal — the harness's own web tools from a tab that is
// CONTAMINATED but not latched EXTERNAL. It needs its own text because the two
// above name a cause ("already used a local-capability tool") that did not
// happen in this state, and a refusal stating a cause it did not check is F-23.
const CIMP_REFUSAL_NATIVE_WEB_TAINTED = "REFUSED (security boundary): external content has already entered this conversation, so this harness's own web tools — fetch and search — are unavailable to it. Local tools are unaffected. This cannot be unlocked, re-asked for, or worked around; it is enforced outside the model, and spawning a sub-agent reaches the same boundary. Use the project's proxied research tools if you have them, or answer with what you have gathered.";
// #48 (F-23) itself: the FOURTH refusal — the `local` latch a USER put there with
// the decision-15 workflow flip. Same refusal, different sentence: the one above
// this pair blames a local-capability tool call, and after a flip no such call
// happened. Which of the two is served is decided by `local_by_user_flip`, a fact
// the app RECORDED when it applied the override — not by anything this process,
// this hook or the model can say about itself. Both are fixed strings baked at
// spawn, so a tab launched before this build still serves the old sentence.
const CIMP_REFUSAL_NATIVE_WEB_USER_LOCAL = "REFUSED (security boundary): the user restored this session's local capability, which closed its external side in the same move, so this harness's own web tools — fetch and search — are unavailable for the remainder of this session. No tool call of yours caused this and none can undo it: the decision was taken outside the conversation. This cannot be unlocked, re-asked for, or worked around; it is enforced outside the model, and spawning a sub-agent reaches the same boundary. Continue with the tools you still have, or answer with what you have gathered.";
// This hook is serialized into EVERY tool call, so the common path must be
// in-memory. 2s is short enough that a latch engaged by a proxied `ddg` fetch
// (which this process never sees) is honoured almost immediately, and long
// enough that a burst of file reads costs one round trip, not twenty.
const CIMP_GATE_TTL_MS = 2000;
// The fail-open verdict, and the initial value: gate off, nothing latched,
// nothing known about contamination (#48, F-13 — `false` is the fail-open value
// for that field too), and no user flip on record (#48, F-23 — `false` there
// selects the pre-F-23 refusal, which refuses exactly what it always did).
let CIMP_GATE_STATE = { at: 0, gate: false, latch: "open", contaminated: false, local_by_user_flip: false };
// Monotonic invalidation counter (#48, H-1). Validation and invalidation used
// to speak different languages: the query RE-ASSIGNED `CIMP_GATE_STATE` to a
// fresh object stamped with a `now` captured BEFORE its fetch, while the beacon
// invalidated by MUTATING `.at = 0` on whatever object was current. A query
// still in flight when a beacon fired therefore overwrote the invalidation with
// its pre-beacon verdict and re-validated it for a full TTL — `read` and
// `webfetch` dispatched concurrently, and every local tool for the next 2 s ran
// against an `open` latch the beacon had already moved to EXTERNAL. Both halves
// now move this counter instead, so a stale reply is recognizable as stale.
let CIMP_GATE_EPOCH = 0;
// Native WEB tool calls of THIS tab that have been admitted but whose beacon
// POST has not landed yet (#48, M-15).
//
// The epoch above closes one half of the race — a query already IN FLIGHT when
// the beacon fires. It cannot close the other half: a query issued DURING the
// beacon POST starts at the already-bumped epoch, and the app has not engaged
// the latch yet (the POST that engages it is the one still in flight), so the
// reply is a truthful, genuinely pre-contamination `open`. `settle` saw nothing
// wrong with it and cached it for a full CIMP_GATE_TTL_MS — the exact window
// the latch exists to close, with a `read` admitted after a `webfetch` was.
//
// This counter is what makes that window visible locally. It is read in two
// places and TIGHTENS in both: `settle` refuses to cache across it, and the
// gate treats it as an EXTERNAL latch for local-capability tools. It never
// loosens anything, which is why an unauthenticated in-process counter is
// allowed to drive it at all — the authority to REFUSE nothing (`gate: false`)
// still comes from the app, and this can only ever add a refusal on top of a
// `gate: true` the app issued.
//
// Bounded by the beacon POST's own `AbortSignal.timeout(2000)` and decremented
// in a `finally`, so it cannot leak. A beacon whose promise never settles at
// all would pin it — but that same promise is awaited by the hook, so the web
// tool call itself would already be hung; the counter outliving it is not a new
// failure mode.
let CIMP_WEB_PENDING = 0;

// Resolve this tab's gate verdict from the app, cached for CIMP_GATE_TTL_MS.
//
// NEVER THROWS and NEVER DENIES ON DOUBT: an unreachable loopback, a non-200, a
// malformed body, a rotated token, an unknown latch label — every one of them
// returns { gate: false }, which refuses nothing. That is the locked V32
// posture for this control and the reason its toggle can ship without adding a
// second failure mode: "the app is down" and "the app says there is no gate"
// have to be the same behaviour, or a crash becomes a lockout.
//
// The failed verdict is cached like a successful one, so a dead app costs one
// attempt per TTL rather than one per tool call.
async function cimpGateState() {
  const now = Date.now();
  if (now - CIMP_GATE_STATE.at < CIMP_GATE_TTL_MS) return CIMP_GATE_STATE;
  // The epoch this query started at. Anything that invalidates the cache bumps
  // it, so a reply that resolves after an invalidation is recognizably about a
  // latch that has already moved.
  const epoch = CIMP_GATE_EPOCH;
  // …and whether a beacon was ALREADY in flight when it started (#48, M-15).
  // Together the two cover every beacon that overlaps this query at all: one
  // that starts while the query is in flight moves the epoch, and one that
  // started earlier but overlaps was, by definition of overlapping, still
  // pending right here. So `settle` below can decide "did any contamination
  // event touch my window" from two integers read at the same instant.
  const pendingAtStart = CIMP_WEB_PENDING;
  const open = { at: now, gate: false, latch: "open", contaminated: false, local_by_user_flip: false };
  // Commit a verdict to the CACHE only if no contamination event touched this
  // query's window; answer with it either way.
  //
  // The asymmetry is deliberate (#48, M-15). App-side the latch is STICKY — it
  // only ever tightens, open → external/local, and never re-opens — so any
  // verdict that comes back is a LOWER BOUND on the real restriction. Applying
  // one late can therefore under-refuse but never over-refuse, which is exactly
  // the fail-open posture this control is required to have, and it is what this
  // caller got before #48 anyway. What must never happen is CACHING it: that is
  // what turned a single pre-contamination `open` into a full CIMP_GATE_TTL_MS
  // of admitted local tools. Leaving the cache empty costs one round trip on
  // the next tool call and re-reads a latch that has by then moved.
  //
  // Returning `v` rather than `open` also keeps the in-flight window
  // enforceable: `open` carries `gate: false`, so a query that answered with it
  // would skip the deny site's `st.gate === true` guard entirely and admit the
  // very call the window exists to refuse.
  const settle = (v) => {
    if (CIMP_GATE_EPOCH === epoch && pendingAtStart === 0) CIMP_GATE_STATE = v;
    return v;
  };
  try {
    const r = await CIMP_FETCH(CIMP_LOOPBACK + "/latch/state", {
      method: "POST",
      headers: { authorization: "Bearer " + CIMP_TOKEN, "content-type": "application/json" },
      body: JSON.stringify({ chp: CIMP_CHP, tab: CIMP_TAB_ID, consumer: "opencode" }),
      signal: AbortSignal.timeout(1500),
    });
    if (!r || !r.ok) return settle(open);
    const j = await r.json();
    // The backend resolves the whole three-level hierarchy (and ANDs in the
    // taint-latch feature) — this side holds no part of it and asserts nothing
    // beyond the two fields' types.
    if (!j || j.gate !== true || typeof j.latch !== "string") return settle(open);
    // #48 (F-13): `contaminated` is read `=== true` and is DELIBERATELY NOT part
    // of the guard above. Requiring it would turn a reply that merely lacks the
    // field — an older loopback, a schema change — into `settle(open)`, i.e. a
    // TOTAL gate bypass including the latch half. Read defensively instead: a
    // missing or non-boolean value is `false`, which loses only the one refusal
    // this field adds and keeps everything else enforced.
    // #48 (F-23): `local_by_user_flip` rides in on the same defensive read as
    // `contaminated`, and is likewise NOT in the guard above — it selects a
    // message, so requiring it would trade the whole gate for a sentence.
    return settle({ at: now, gate: true, latch: j.latch, contaminated: j.contaminated === true, local_by_user_flip: j.local_by_user_flip === true });
  } catch (_e) {
    return settle(open);
  }
}

// ── V35 Phase I: the CHP hello (design D3) ──────────────────────────────────
//
// Fired ONCE, here, while this module is being evaluated — which for a generated
// plugin is per TAB LAUNCH, exactly the spawn-baked moment worth stamping. It
// tells the app which protocol version this file speaks, and which CHP events it
// will actually push with this tab's flags applied. A capability absent from
// `serves` is UNAVAILABLE, not broken.
//
// NOTHING GATES ON IT. The app records and displays the declaration; no cImp
// feature consults it (that is Phase L). In particular `tool.gate` appearing
// here is not a trust claim — the gate's authority is the app computing the
// verdict at /latch/state, and this file's only power is to refuse MORE than it
// was told to.
//
// IT MUST NOT THROW, and the shape below is written for that and nothing else.
// A module that throws while loading takes the harness's whole plugin load down
// with it — the same hazard the CIMP_FETCH binding above is guarded against —
// so the dispatch sits inside a try/catch, the result is only `.catch`ed after
// being checked for a `.catch`, and the reply is never read. A dead app, a
// rotated token or a runtime with no fetch all end as "unannounced".
try {
  if (CIMP_TAB_MATCH) {
    const hello = CIMP_FETCH(CIMP_LOOPBACK + "/session/hello", {
      method: "POST",
      headers: { authorization: "Bearer " + CIMP_TOKEN, "content-type": "application/json" },
      body: JSON.stringify({
        chp: CIMP_CHP,
        agent: "opencode",
        tab: CIMP_TAB_ID,
        // `harness_version` is deliberately ABSENT: OpenCode exposes no version
        // to a plugin at module scope, and baking in the number cImp last saw
        // would be cImp attesting to itself rather than the harness declaring
        // anything. `docs/CHP.md` § 6.2.
        serves: ["hello","prompt","memory.event","context.post_edit","taint.beacon","tool.gate","checkpoint.pre_mutation"],
        cannot: [{"id":"assistant_text","why":"OpenCode's plugin API delivers assistant text per completed PART (`experimental.text.complete`) or as the same SSE payload shapes the reader already consumes (`event`), so pushing it would either change the segmenter's unit or move no tier — the `/event` SSE reader stays this harness's declared fallback (`opencode.sse.events`)"},{"id":"session.tool_result","why":"reachable (`tool.execute.after`'s output parameter carries the result text) but unconsumed: OpenCode usage is estimate-only from tool-call input args, so wiring it would add a capability rather than migrate one"}],
      }),
      signal: AbortSignal.timeout(2000),
    });
    if (hello && typeof hello.catch === "function") hello.catch(() => {});
  }
} catch (_e) {}

// V24 Phase F: child session id -> parent session id, learned from
// `session.created` events. Sub-agent (task-tool) sessions are always created
// while this plugin is running, so a session-lifetime Map is sufficient; usage
// POSTs from a session in this map carry `parent_session_id` so the backend can
// roll the spend up to the parent (mirrors the Claude sub-agent contract).
const CIMP_PARENTS = new Map();

export default async (input) => ({
  // V13 Phase C: this POST always fires (not gated on CIMP_INJECT_ENABLED)
  // so the app-side prompt-tap checkpoint trigger sees every prompt even
  // when injection is off — only APPLYING the returned text to the draft is
  // gated. Mirrors the Claude `--context-hook` shim, which always POSTs too.
  "chat.message": async (inp, out) => {
    if (!CIMP_TAB_MATCH) return;
    const p = out.parts.find((x) => x.type === "text");
    if (!p || !p.text) return;
    try {
      const r = await CIMP_FETCH(CIMP_LOOPBACK + "/context/retrieve", {
        method: "POST",
        headers: { authorization: "Bearer " + CIMP_TOKEN, "content-type": "application/json" },
        // V33: `tab` rides along so the prompt-tap checkpoint this POST fires
        // can be attributed to THIS tab — `agent` is the harness name, shared
        // by every OpenCode tab, and `CIMP_TAB_ID` is already baked into this
        // file for the beacon/gate. Same identity, one source.
        body: JSON.stringify({ chp: CIMP_CHP, cwd: input.directory, prompt: p.text, session_id: inp.sessionID, agent: "opencode", tab: CIMP_TAB_ID }),
        signal: AbortSignal.timeout(600),
      });
      const j = await r.json();
      if (CIMP_INJECT_ENABLED && j && j.ok && j.text) p.text += "\n\n" + j.text;
    } catch (_e) {}
  },
  // Two halves, in this order: the V32 Phase H GATE (may deny) and then the
  // V32 Phase F native-web BEACON (report-only, never throws).
  //
  // The beacon fires BEFORE the tool runs so the latch is engaged by the time
  // the fetched bytes exist, and it NEVER throws or rejects —
  // `tool.execute.before` denies by throwing (the E2 spike verdict), so any
  // escaping error in that half would turn a report-only sensor into a silent
  // deny of the user's own web tool. Everything in it is inside one try/catch,
  // the fetch is awaited only to keep the ordering honest, and its own
  // rejection is caught by the same block. A dead app, a rotated token or a 2s
  // stall all end as "unreported", never as "refused".
  "tool.execute.before": async (inp) => {
    // ── V32 Phase H: the GATE half, and it runs FIRST. ──────────────────────
    // Deliberately OUTSIDE the try/catch below, because throwing is how this
    // hook denies (the E2 spike verdict) — the only escaping error in this file,
    // and only ever on a definite deny verdict. Args are NEVER rewritten: arg
    // mutation is the buggy upstream path (#31680/#39674/#37963).
    //
    // Ordering matters: gate before beacon, so a refused web call does not first
    // engage the latch and contaminate the conversation. That is the same
    // property the proxy's `gate` has — a refused call never moves the latch.
    if (CIMP_NATIVE_GATE_ENABLED && CIMP_TAB_MATCH && inp) {
      const local = CIMP_NATIVE_LOCAL_TOOLS.has(inp.tool);
      const web = CIMP_WEB_TOOLS.has(inp.tool);
      // An unlisted name (task, skill, todowrite, question) is UNGATED and costs
      // no round trip — the check is a Set lookup before anything is awaited.
      if (local || web) {
        const st = await cimpGateState();
        if (st.gate === true) {
          // #48 (M-15): a native web tool of this tab that has ALREADY been
          // admitted, and whose beacon POST is still in flight, contaminates
          // this conversation exactly as much as one the app has heard about —
          // the app's reply merely predates it. Read here, at the deny site, so
          // NO cache path can bypass it: a cached verdict, a fresh verdict and a
          // fail-open verdict all pass through this one expression.
          //
          // Tighten-only, and deliberately only in the LOCAL direction. It ADDS
          // "external" to the local test and touches nothing else, so it can
          // never turn a `local` latch's web refusal (the line below) into an
          // admission — the one way a local signal could have loosened the gate.
          const external = st.latch === "external" || CIMP_WEB_PENDING > 0;
          // #48 (F-13): `contaminated` has been on this wire since Phase H and
          // nothing read it. Read it HERE, at the same deny site every cache
          // path funnels through, and ONLY in the WEB direction.
          //
          // Once external content has entered this conversation, the harness's
          // own web tools are its unproxied way OUT — no beacon in `off`/`deny`
          // mode, no latch, no budget, no SSRF screen. The other direction is
          // deliberately untouched: contamination's cost to LOCAL capability is
          // persistence, which the app-side write quarantine already enforces,
          // and refusing local tools here would make "switch to local" restore
          // the proxied half of a surface and not the native half.
          //
          // Why `=== "open"` and not `!== "external"`: `cimpGateState`'s
          // contract is that an UNKNOWN latch label denies nothing, and that
          // promise is delivered by the negative form of these tests. Why
          // `=== true`: a missing field must read `false`, i.e. fail open.
          //
          // A clear (`clear_contamination` app-side) reaches this within one
          // CIMP_GATE_TTL_MS and needs no invalidation: the epoch exists so a
          // TIGHTENING cannot be overwritten by a stale verdict, and a loosening
          // that lands late costs at most one TTL of over-refusal — exactly the
          // latency `FlipLocal` already has for the local direction. The app
          // process has no inbound channel into this plugin; the TTL is the
          // mechanism, not a shortcut around one.
          const tainted = st.contaminated === true && st.latch === "open";
          // #48 (F-23): WHICH refusal, never WHETHER. `local_by_user_flip` is a
          // fact the app recorded when it applied the user's workflow flip, read
          // here for the one purpose of not blaming a tool call that never
          // happened. Read `=== true` like `contaminated` and for the same
          // reason: a reply that lacks the field (an older loopback) must lose
          // only the better sentence, never a refusal — so the fallback is the
          // pre-F-23 constant, which is what this line always served.
          const userLocal = st.local_by_user_flip === true;
          if (local && external) throw new Error(CIMP_REFUSAL_NATIVE_LOCAL);
          if (web && st.latch === "local") throw new Error(userLocal ? CIMP_REFUSAL_NATIVE_WEB_USER_LOCAL : CIMP_REFUSAL_NATIVE_WEB);
          if (web && tainted) throw new Error(CIMP_REFUSAL_NATIVE_WEB_TAINTED);
        }
      }
    }
    // ── V33 Phase F: the CHECKPOINT half — report-only, never throws. ───────
    //
    // AFTER the gate, deliberately: a refused call never happened, and
    // checkpointing before it would leave a Timeline row blaming a tool that
    // did not run — the same ordering rule the beacon half follows below, and
    // the same one the proxy's own gate has (a refused call never moves the
    // latch).
    //
    // Its OWN try/catch, not the beacon's: these are two independent reports,
    // and folding them together would mean a slow app that times out the
    // checkpoint POST also skipped the web beacon (or vice versa). Everything
    // inside is swallowed — `tool.execute.before` denies by THROWING, so an
    // escaping error here would turn a checkpoint into a silent refusal of the
    // user's own edit.
    //
    // The POST is AWAITED. That is the point of the feature — a checkpoint
    // taken after the write is a checkpoint of the damage — and it is safe
    // here in a way it is not in the Claude shim, whose fail-open contract
    // forbids waiting on the app: this hook's timeout semantics are ours, so
    // the 2s abort signal below IS the bound, and it degrades to "unreported",
    // never to "refused". Cost is bounded app-side too: the checkpoint
    // throttle is per `(project root, tab)`, so a burst of edits inside one
    // `checkpoint_min_gap_s` window costs one snapshot, not one per call.
    try {
      if (CIMP_CHECKPOINT_ENABLED && CIMP_TAB_MATCH && inp && CIMP_MUTATING_TOOLS.has(inp.tool)) {
        await CIMP_FETCH(CIMP_LOOPBACK + "/workbench/tool_checkpoint", {
          method: "POST",
          headers: { authorization: "Bearer " + CIMP_TOKEN, "content-type": "application/json" },
          body: JSON.stringify({
            chp: CIMP_CHP,
            tab: CIMP_TAB_ID,
            agent: "opencode",
            tool: inp.tool,
            cwd: input.directory,
            session_id: inp.sessionID,
          }),
          signal: AbortSignal.timeout(2000),
        });
      }
    } catch (_e) {}
    // ── V32 Phase F: the BEACON half — report-only, and it still never throws.
    try {
      if (!CIMP_TAB_MATCH || !inp || !CIMP_WEB_TOOLS.has(inp.tool)) return;
      // A native web tool is about to run, so whatever the gate cached a moment
      // ago describes a latch that is about to move. Invalidate here, ABOVE the
      // beacon's own enable guard and BEFORE the POST:
      //
      //   * above the guard, because the gate can be ON while the beacon is off
      //     — `off`/`deny` native-web mode with the gate switched on, where
      //     nothing invalidated the cache at all (#48, H-1's second half);
      //   * before the POST, so a fetch that throws still leaves the stale
      //     verdict dropped rather than live for the rest of its TTL.
      //
      // Bumping the epoch is what makes this stick: a query already in flight
      // can no longer commit its pre-beacon verdict on top of this.
      //
      // #48 (F-14) — WHAT THIS DOES AND DOES NOT COVER. It used to be justified
      // as covering "the most hardened combination available", which claimed
      // more than it delivers, and the claim was the defect. Two honest bounds:
      //   * with the beacon OFF the invalidation still fires, but only for this
      //     tab's OWN native web tools, and in that mode nothing reports the
      //     call — so the re-query answers with whatever the app already knew,
      //     usually `open`. The value is that the placement is ABOVE the enable
      //     guard, i.e. structural, not that it learns anything new;
      //   * a PROXIED `ddg` fetch does move the latch app-side and triggers NO
      //     invalidation here at all — this process never sees it. That path is
      //     covered by CIMP_GATE_TTL_MS alone (≤ 2 s), by design: the app has no
      //     inbound channel into this plugin.
      CIMP_GATE_EPOCH++;
      CIMP_GATE_STATE = { at: 0, gate: false, latch: "open", contaminated: false, local_by_user_flip: false };
      // #48 (M-15): open the in-flight window HERE, on the statement after the
      // epoch bump, and close it in the `finally` below. The adjacency is the
      // whole guarantee — there is no `await` between the two, so this engine
      // cannot run another hook in between, and therefore no gate query can
      // start in the sliver where the epoch has moved but the window is not yet
      // open. A test pins that no `await` appears between them. It is raised
      // above the enable guard for the same reason the epoch bump is, and the
      // `try` starts before the guard so the `return` for a disabled beacon
      // closes the window on its way out.
      CIMP_WEB_PENDING++;
      try {
        if (!CIMP_BEACON_ENABLED) return;
        await CIMP_FETCH(CIMP_LOOPBACK + "/latch/beacon", {
          method: "POST",
          headers: { authorization: "Bearer " + CIMP_TOKEN, "content-type": "application/json" },
          body: JSON.stringify({
            chp: CIMP_CHP,
            tab: CIMP_TAB_ID,
            consumer: "opencode",
            tool: inp.tool,
            cwd: input.directory,
            session_id: inp.sessionID,
          }),
          signal: AbortSignal.timeout(2000),
        });
      } finally {
        CIMP_WEB_PENDING--;
      }
    } catch (_e) {}
  },
  "tool.execute.after": async (inp) => {
    if (!CIMP_TAB_MATCH) return;
    try {
      const body = {
        chp: CIMP_CHP,
        cwd: input.directory,
        session_id: inp.sessionID,
        agent: "opencode",
        tool: inp.tool,
        args: inp.args,
      };
      // V24 Phase F: a task-tool CHILD (sub-agent) session stamps its parent so
      // the backend mirrors the Claude sidechain contract — the child's tool
      // events are dropped and only the parent is marked live (the child's real
      // token spend rolls up to the parent via the `event` usage hook below).
      const parent = CIMP_PARENTS.get(inp.sessionID);
      if (parent) body.parent_session_id = parent;
      await CIMP_FETCH(CIMP_LOOPBACK + "/memory/event", {
        method: "POST",
        headers: { authorization: "Bearer " + CIMP_TOKEN, "content-type": "application/json" },
        body: JSON.stringify(body),
        signal: AbortSignal.timeout(600),
      });
    } catch (_e) {}
    // V12 Phase F (6a/6b): best-effort, fire-and-forget — OpenCode's hook
    // return value isn't verified to carry context back to the model (the F0
    // spike scope), so this doesn't await/use the response; the server-side
    // debounce/diff/park still runs, and a parked block reaches the model via
    // the next `chat.message` retrieve above.
    if (CIMP_AUTO_CHECK_ENABLED && CIMP_EDIT_TOOLS.has(inp.tool)) {
      const filePath = (inp.args && (inp.args.filePath || inp.args.path)) || "";
      CIMP_FETCH(CIMP_LOOPBACK + "/context/post_edit", {
        method: "POST",
        headers: { authorization: "Bearer " + CIMP_TOKEN, "content-type": "application/json" },
        body: JSON.stringify({
          chp: CIMP_CHP,
          cwd: input.directory,
          session_id: inp.sessionID,
          file_path: filePath,
          tool_name: inp.tool,
          // #48 (M-7): the identity `/context/post_edit`'s taint gate resolves
          // a latch scope from. This route executes the project's configured
          // checks; without a tab it resolves no scope and is ungated.
          agent: "opencode",
          tab: CIMP_TAB_ID,
        }),
        signal: AbortSignal.timeout(600),
      }).catch((_e) => {});
    }
  },
  // V24 Phase F: OpenCode's real per-turn token tap (spike-confirmed against
  // 1.18.1). `chat.message` fires on the USER prompt and carries no tokens, so
  // forwarding happens here on the assistant `message.updated` event once the
  // turn has completed. The message is emitted first with zero tokens, then
  // re-emitted (duplicated) with final tokens — gate on `time.completed` and
  // let the backend upsert-by-msg_id absorb the duplicate. Never gated on the
  // inject/auto-check flags (usage is always recorded); best-effort, non-blocking.
  event: async ({ event }) => {
    if (!CIMP_TAB_MATCH) return;
    try {
      if (!event) return;
      const info = event.properties && event.properties.info;
      if (event.type === "session.created") {
        // A sub-agent (task-tool) child session announces its parent here.
        if (info && info.id && info.parentID) CIMP_PARENTS.set(info.id, info.parentID);
        return;
      }
      if (event.type !== "message.updated") return;
      if (!info || info.role !== "assistant" || !info.time || !info.time.completed) return;
      const tok = info.tokens || {};
      const cache = tok.cache || {};
      const body = {
        chp: CIMP_CHP,
        cwd: input.directory,
        agent: "opencode",
        kind: "usage",
        session_id: info.sessionID,
        msg_id: info.id,
        // Bare modelID (no providerID) — consistent with how Claude sessions
        // store bare model ids and with matchPricing's model_prefix semantics.
        model: info.modelID,
        in_tok: (tok.input || 0),
        // reasoning folds into output (priced as output everywhere it matters).
        out_tok: ((tok.output || 0) + (tok.reasoning || 0)),
        cache_read: (cache.read || 0),
        cache_make: (cache.write || 0),
      };
      const parent = CIMP_PARENTS.get(info.sessionID);
      if (parent) body.parent_session_id = parent;
      await CIMP_FETCH(CIMP_LOOPBACK + "/memory/event", {
        method: "POST",
        headers: { authorization: "Bearer " + CIMP_TOKEN, "content-type": "application/json" },
        body: JSON.stringify(body),
        signal: AbortSignal.timeout(600),
      });
    } catch (_e) {}
  },
});
